[package]
name = "backend"
version = "0.1.0"
edition = "2021"
authors = ["Matthew Scheffel <matt@dataheck.com>"]

[dependencies]
chrono = { version = "0.4" }
diesel = { version = "2.0", features = ["postgres", "chrono", "r2d2"] }
dotenv = "0.15.0"